/**
 * Typed IPC channel identifiers.
 * All renderer ↔ main communication must use channels defined here.
 */
export const IPC_CHANNELS = {
  APP_GET_INFO: 'app:get-info',
  APP: {
    GET_INFO: 'app:get-info',
    DB_HEALTH: 'app:db-health',
  },
  CATALOG: {
    CATEGORIES_LIST: 'catalog:categories-list',
    CATEGORY_CREATE: 'catalog:category-create',
    CATEGORY_UPDATE: 'catalog:category-update',
    BRANDS_LIST: 'catalog:brands-list',
    BRAND_CREATE: 'catalog:brand-create',
    BRAND_UPDATE: 'catalog:brand-update',
    UNITS_LIST: 'catalog:units-list',
    UNIT_CREATE: 'catalog:unit-create',
    UNIT_UPDATE: 'catalog:unit-update',
  },
  PRODUCTS: {
    LIST: 'products:list',
    GET: 'products:get',
    CREATE: 'products:create',
    UPDATE: 'products:update',
    SEARCH: 'products:search',
  },
  PRODUCT_VARIANTS: {
    LIST: 'product-variants:list',
    CREATE: 'product-variants:create',
    UPDATE: 'product-variants:update',
  },
  BARCODES: {
    LIST: 'barcodes:list',
    ADD: 'barcodes:add',
    DEACTIVATE: 'barcodes:deactivate',
    GENERATE_INTERNAL: 'barcodes:generate-internal',
    VALIDATE_EAN13: 'barcodes:validate-ean13',
  },
  PRINT_JOBS: {
    LIST: 'print-jobs:list',
    CREATE: 'print-jobs:create',
    UPDATE_STATUS: 'print-jobs:update-status',
    RETRY: 'print-jobs:retry',
    CLEAR_PRINTED: 'print-jobs:clear-printed',
  },
  SALES: {
    CREATE: 'sales:create',
    GET_BY_ID: 'sales:get-by-id',
    SEARCH: 'sales:search',
    REPRINT: 'sales:reprint',
    VOID: 'sales:void',
    LIST_RECENT: 'sales:list-recent',
    LOOKUP_BARCODE: 'sales:lookup-barcode',
    HOLD_BILL: 'sales:hold-bill',
    GET_HELD_BILLS: 'sales:get-held-bills',
    RESUME_HELD_BILL: 'sales:resume-held-bill',
    DELETE_HELD_BILL: 'sales:delete-held-bill',
  },
  INVENTORY: {
    ADJUST: 'inventory:adjust',
    LIST_MOVEMENTS: 'inventory:list-movements',
    GET_KPIS: 'inventory:get-kpis',
    GET_LOW_STOCK: 'inventory:get-low-stock',
    GET_VARIANT_STOCK: 'inventory:get-variant-stock',
    LIST_STOCK_SUMMARY: 'inventory:list-stock-summary',
  },
  SUPPLIERS: {
    LIST: 'suppliers:list',
    GET_BY_ID: 'suppliers:get-by-id',
    CREATE: 'suppliers:create',
    UPDATE: 'suppliers:update',
    GET_LEDGER: 'suppliers:get-ledger',
    RECORD_PAYMENT: 'suppliers:record-payment',
  },
  PURCHASES: {
    LIST: 'purchases:list',
    GET_BY_ID: 'purchases:get-by-id',
    CREATE: 'purchases:create',
    GET_KPIS: 'purchases:get-kpis',
  },
  CUSTOMERS: {
    LIST: 'customers:list',
    GET_BY_ID: 'customers:get-by-id',
    LOOKUP_PHONE: 'customers:lookup-phone',
    CREATE: 'customers:create',
    UPDATE: 'customers:update',
    GET_LEDGER: 'customers:get-ledger',
    RECORD_PAYMENT: 'customers:record-payment',
    GET_KPIS: 'customers:get-kpis',
  },
  AUTH: {
    LOGIN: 'auth:login',
    LOGOUT: 'auth:logout',
    GET_CURRENT_USER: 'auth:get-current-user',
    CHANGE_PASSWORD: 'auth:change-password',
  },
  USERS: {
    LIST: 'users:list',
    GET_BY_ID: 'users:get-by-id',
    CREATE: 'users:create',
    UPDATE: 'users:update',
    RESET_PASSWORD: 'users:reset-password',
    GET_PERMISSIONS: 'users:get-permissions',
    UPDATE_PERMISSIONS: 'users:update-permissions',
  },
  AUDIT: {
    LIST: 'audit:list',
  },
  DASHBOARD: {
    GET_KPIS: 'dashboard:get-kpis',
    GET_TREND: 'dashboard:get-trend',
    GET_TOP_PRODUCTS: 'dashboard:get-top-products',
    GET_PAYMENT_BREAKDOWN: 'dashboard:get-payment-breakdown',
    GET_LOW_STOCK: 'dashboard:get-low-stock',
    GET_ACTIVITY: 'dashboard:get-activity',
  },
  EXPENSE_CATEGORIES: {
    LIST: 'expense-categories:list',
    CREATE: 'expense-categories:create',
    UPDATE: 'expense-categories:update',
  },
  EXPENSES: {
    LIST: 'expenses:list',
    GET_BY_ID: 'expenses:get-by-id',
    CREATE: 'expenses:create',
    UPDATE: 'expenses:update',
    VOID: 'expenses:void',
    GET_REPORT: 'expenses:get-report',
    GET_SUMMARY: 'expenses:get-summary',
  },
  CASH: {
    OPEN_SESSION: 'cash:open-session',
    LIST_SESSIONS: 'cash:list-sessions',
    GET_CURRENT: 'cash:get-current',
    LIST_MOVEMENTS: 'cash:list-movements',
    CASH_IN: 'cash:cash-in',
    CASH_OUT: 'cash:cash-out',
    CLOSE_SESSION: 'cash:close-session',
    GET_REPORT: 'cash:get-report',
  },
  RETURNS: {
    SEARCH_SALES: 'returns:search-sales',
    SEARCH_PURCHASES: 'returns:search-purchases',
    HISTORY: 'returns:history',
    CREATE_SALES: 'returns:create-sales',
    CREATE_PURCHASE: 'returns:create-purchase',
    CREATE_SALES_EXCHANGE: 'returns:create-sales-exchange',
    CREATE_PURCHASE_EXCHANGE: 'returns:create-purchase-exchange',
    GET_SALES_BY_ID: 'returns:get-sales-by-id',
    GET_PURCHASE_BY_ID: 'returns:get-purchase-by-id',
    GET_SALES_EXCHANGE_BY_ID: 'returns:get-sales-exchange-by-id',
    GET_PURCHASE_EXCHANGE_BY_ID: 'returns:get-purchase-exchange-by-id',
  },
  REPORTS: {
    GET_SALES: 'reports:get-sales',
    GET_PURCHASES: 'reports:get-purchases',
    GET_INVENTORY: 'reports:get-inventory',
    GET_MOVEMENTS: 'reports:get-movements',
    GET_SUPPLIERS: 'reports:get-suppliers',
    GET_CUSTOMERS: 'reports:get-customers',
    GET_PROFIT_SUMMARY: 'reports:get-profit-summary',
    EXPORT: 'reports:export',
  },
  SETTINGS: {
    GET_ALL: 'settings:get-all',
    GET: 'settings:get',
    SET: 'settings:set',
    SET_MANY: 'settings:set-many',
  },
  NOTIFICATIONS: {
    LIST: 'notifications:list',
    GET_UNREAD_COUNT: 'notifications:get-unread-count',
    MARK_AS_READ: 'notifications:mark-as-read',
    MARK_ALL_AS_READ: 'notifications:mark-all-as-read',
    DISMISS: 'notifications:dismiss',
    UNDISMISS: 'notifications:undismiss',
  },
  LICENSING: {
    GET_STATUS: 'licensing:get-status',
    GET_MACHINE_CODE: 'licensing:get-machine-code',
    ACTIVATE: 'licensing:activate',
    DEACTIVATE: 'licensing:deactivate',
  },
  BACKUP: {
    CREATE: 'backup:create',
    LIST: 'backup:list',
    GET_STATS: 'backup:get-stats',
    VALIDATE: 'backup:validate',
    RESTORE: 'backup:restore',
    SELECT_FILE: 'backup:select-file',
    DOWNLOAD_DB: 'backup:download-db',
  },
  HARDWARE: {
    GET_PRINTERS: 'hardware:get-printers',
    TEST_PRINT: 'hardware:test-print',
    OPEN_DRAWER: 'hardware:open-drawer',
  },
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)['APP_GET_INFO'];

